dist: bionic
language: generic

addons:
  apt:
    packages:
      - libgmp-dev

services:
  - docker

stages:
  - test
  - package
  - name: publish
    if: branch = master OR tag =~ ^v.*

env:
  global:
    # BINTRAY_API_USER
    - secure: "LT5Ys4YxitulxL2BwNErmb/4d6vlhdX4GPiJvEqMaZqlzPavvgXAJNL5oC8yRVe9lHd3kjiSQG9rjzwU5kFMdw/Xmg6Xzz6r4PGz1F/0KzasfrB1guHnyhBU3xuFqkawJEJe1L2hcxFGn1vv8j2qIore0FA0YiChVOcxEWOKA7qlC0BV7qLnP4D+YRrWKW1LrLi2FPKlw2lROzrJWT639Z0GIl6uCxaUqvxr4pTZVJoDxA+SFge1iGYSzfzxOoYEDfMChHSulLCJ3eOpur40emGP4DmOk+z2XJC4pZ7sNUSzNH0zKSoaRr3Htc3clNlrYcv+WI+BgHZih8HhZ1X0OcjwY0//UbSj15uTtoHgtKbeuaf8HQUEc0yMuIvBcpKp/7yrNvUxEm0QwHpKa1za1lq4wv9786spwMJnVlB2HefOdsMDKPmwloD8LiTWw3ifu1oJHs2pd5kBC211swuWTl9QiQp/x0neVucH/1L9ed3kRBp0jAntr68Lonfy+Z3CKyXwu1Mqq6YiFVWh11qGiKiyGV32lGI1TsEW1+cMab95xoBYbPr0pL/AjJlbmhZGJHWy2aDroq9oZ+BrH+M/7CcbrGYHLFr5w/SL4YV7GUE9npdWrkSIrr0rXcJ+ZxgtcgwcvFq2luiYFSgcMm0mR7GMvQ1bRtEWdV/qT3t2z9M="
    # BINTRAY_API_KEY
    - secure: "hojtYaKu4W81hO6TSIQrNPhAIWId6kJLPuwgVvlEGL8VbyCIaccdfsLVdFgS3ULIqE6jnohCPq/8cY0IjYJrQRDqZ33JY1GnO4k36zzOe06W+AvTXwgpsvnN8b5/4h5GDlUQJJmvI20Wbe8HQ14fRmUuut9rFukQ2zVZ76n2hkcd+w0hrAOU66K8HV26oXCKXeXkFNMNJ7zZMHu/yNE4yXO6AIIyTObfKqvE3U4GqkqOJoshB5vMYmvrDPHKH/uBPXwwfZFH90M1LmHYQlz34ox+q49B2RckTIWNuJgm7I9At6wUjEvpzXFSH/evnRcA7Io9llIURlY+WFZcIW0hWFwca3LkI5sWIJoQ903LFzcnNvHqgyIx7Krk9TXoF+7WylvLeNZGBA/h19USMM0TTzC5Nyzc8ZkXMgOKmkEumazMJvL+nAppFV3PICqb2GFFzGpaKNZ6n4OOEdbFSsFxxUIV4Q0utezmhtFtxGGqijaz0cEWlszQLU0jXYSmK02nSDn6EF3EGEZS0mP22Q39IP65OaMoJ05a7ChdGs0s8HtC1EuHXZY5hMTng7S84u+umgahdpFl0lwIXcjCawDk251G0Rp/+r8KRtm8LZfQgTkjKTYN6RPWFT4obs7VefKEAay8tXZVcYGnG0MsvypNzn75qqVTjsDNJxm1c1LZUSo="
    # DEPLOY_KEY
    - secure: "bHBpco7QFXghA9BdE8LS1DTrkHpR49N2oFHuQnjC1cP1JEdg+liEwq+QK/iFI5FVBG9tLomcW18ZGSYYwf2qA4d1HfJENVWyfJsVUu/I6Q8oLHy+s3n6uZB0l3H4Ee/Wp66Tx8EKf05Ri+tD8L4/R4wHFSN5cMzpkU4qgXgejtomdwKRQrofGOI6KXs/wY4YtNd1nY/CLgXXr0eyCOD/K2AagwTWywBJIxBlptxgZJQV9PeGJzDiQ1i55CCzJcd9k5X4vgnxjFcdHFdK7E+3YjEhEetwhTKdCdU21/kJEeRXdvITn1DGvY6NWfAyGLh5vFvf7xpgSGM2r93NhiX4Ta7Q6rDIAqEZTR/Avj/SAA38MiWUr4hogK1IZqCEuRKyzxX8hRYbiJHfwkrQ/RjC5734rayEwWWbLNw8AZZ/06fZFxl84XGfyJ+rh/8ZZSOBpVOqniNmjLgK676ssqmglmaFFHcrIjQR2mJTAPRdKf0VRj03i1VTDhYbjJQAgc8+qnddciEUHk7UE92ynnTobdvJ46dNrbSGlC1do/HAIIVo7cCN9wyLRyPLkYbwLoRAUQHSFacmU0ZznE/TdMq7Q8650/qVcb8oajfsDPXYr7LUNMPaOXH2pPu6EFeH9A5lrqx4qeN7GmJss1XxciGqR6GFjT6KipqGrfUL9a8zt6U="

before_install:
  - export PACKAGE_ACTION=$(if [[ "$TRAVIS_BRANCH" == "master" || $TRAVIS_TAG =~ ^v.* ]]; then echo bintray-upload; else echo package; fi)
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - pushd ~/.local/bin && (curl -fL https://getcli.jfrog.io | sh) && popd
  - docker login -u "${BINTRAY_API_USER}" -p "${BINTRAY_API_KEY}" tenpureto-docker-snapshots.bintray.io

.package: &package
  stage: package
  script:
    - make bintray-cache-pull-$OS || true
    - make $PACKAGE_ACTION-$OS
    - "[[ $TRAVIS_BRANCH == master || $TRAVIS_TAG =~ ^v.* ]] && make bintray-cache-push-$OS || true"
  cache:
    directories:
      - .build/$OS/.stack

jobs:
  include:

    - stage: test
      name: Test
      env: CACHE_NAME=test
      before_install:
        - mkdir -p ~/.local/bin
        - export PATH=$HOME/.local/bin:$PATH
        - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      install:
        - make build-deps
      script:
        - make test
      cache:
        directories:
          - $HOME/.stack
    - name: Documentation
      env: CACHE_NAME=test-docs
      script:
        - make npm-ci-docs
        - make test-docs
      cache:
        directories:
          - "$HOME/.npm"

    - <<: *package
      name: Amazon Linux 2
      env: OS=amzn2
    - <<: *package
      name: CentOS 7
      env: OS=centos7
    - <<: *package
      name: Ubuntu 18.04
      env: OS=bionic
    - <<: *package
      name: Debian Buster
      env: OS=buster

    - stage: publish
      name: Native packages
      env: CACHE_NAME=publish
      script: make bintray-publish-rpm bintray-publish-deb
    - name: Documentation
      if: branch = master
      env: CACHE_NAME=publish-docs
      before_script:
        - mkdir -p ~/.ssh
        - echo "${DEPLOY_KEY}" | perl -pe 's/\\n/\n/g' > ~/.ssh/id_ed25519
        - chmod 600 ~/.ssh/id_ed25519
      script:
        - make npm-ci-docs
        - GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519" make publish-docs
      cache:
        directories:
          - "$HOME/.npm"
