name:                tenpureto
version:             0.1.0.0
license:             BSD3
author:              "Roman Timushev"
maintainer:          "rtimush@gmail.com"
copyright:           "2019 Roman Timushev"
description:         Please see the README on GitHub at <https://github.com/rtimush/tenpureto#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- either
- text
- path
- path-io
- containers
- exceptions
- mtl
- transformers
- logging-effect
- prettyprinter
- prettyprinter-ansi-terminal
- terminal-size
- process
- process-extras
- optparse-applicative
- byline
- yaml

library:
  source-dirs: src

executables:
  tenpureto:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenpureto

tests:
  tenpureto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenpureto
