name:                tenpureto
version:             0.1.4
author:              "Roman Timushev"
maintainer:          "rtimush@gmail.com"
github:              "rtimush/tenpureto"
homepage:            "https://github.com/rtimush/tenpureto#readme"
copyright:           "2019 Roman Timushev"
synopsis:            "Simple and flexible project templates"
description:         "Please see the README on GitHub at <https://github.com/rtimush/tenpureto#readme>"

dependencies:
- base >= 4.7 && < 5
- bytestring
- either
- text
- text-icu
- text-regex-replace
- path
- path-io
- directory
- containers
- insert-ordered-containers
- transformers
- prettyprinter
- prettyprinter-ansi-terminal
- terminal-size
- typed-process
- optparse-applicative
- yaml
- aeson
- dotgen
- Glob
- file-embed
- polysemy >= 0.5.0.1
- polysemy-plugin

ghc-options: -O2 -fplugin=Polysemy.Plugin -flate-specialise -fspecialise-aggressively

default-extensions:
- DataKinds
- FlexibleContexts
- GADTs
- LambdaCase
- PolyKinds
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators
- TypeFamilies
- OverloadedStrings

library:
  source-dirs: src

executables:
  tenpureto:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenpureto

tests:
  tenpureto-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tenpureto
    - tasty
    - tasty-discover
    - tasty-smallcheck
    - tasty-hunit
    - smallcheck
