resolver: lts-14.27
packages:
- .
extra-deps:
- hedgehog-classes-0.2.4.1
- polysemy-1.2.2.0
- polysemy-plugin-0.2.3.0
- algebraic-graphs-0.5

nix:
  packages: [ zlib ]

flags:
  polysemy:
    error-messages: False
