name: Build Cache

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build-shell-cache:
    if: github.repository == 'tenpureto/tenpureto'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Cleanup
        run: sudo rm -rf /usr/local/lib/android /opt/ghc
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: tenpureto
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: cachix use iohk
      - run: nix-build -A default.shellFor
  build-ci-cache:
    if: github.repository == 'tenpureto/tenpureto'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: sudo rm -rf /usr/local/lib/android /opt/ghc
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - uses: cachix/cachix-action@v6
        with:
          name: tenpureto
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
      - run: cachix use iohk
      - run: nix-build -A static.tenpureto.components.exes.tenpureto
