name: Build Cache

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0 * * *

jobs:
  build-shell-cache:
    if: github.repository == 'tenpureto/tenpureto'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Cleanup
        run: sudo rm -rf /usr/local/lib/android /opt/ghc
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: tenpureto
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          extraPullNames: iohk
      - run: nix-build -A default.shellFor
        timeout-minutes: 300
  build-ci-cache:
    if: github.repository == 'tenpureto/tenpureto'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: sudo rm -rf /usr/local/lib/android /opt/ghc
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - uses: cachix/cachix-action@v8
        with:
          name: tenpureto
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
          extraPullNames: iohk
      - run: nix-build -A static.tenpureto.components.exes.tenpureto
        timeout-minutes: 300
